{
  "comments": [
    {
      "key": {
        "uuid": "1ab14d0d_3a73a84f",
        "filename": "ansible.cfg",
        "patchSetId": 9
      },
      "lineNbr": 12,
      "author": {
        "id": 1008329
      },
      "writtenOn": "2016-12-21T09:19:07Z",
      "side": 1,
      "message": "I don\u0027t like this implementation that hardcodes the location, it will clearly break on py3. Still, don\u0027t mark it as a blocker unless you already know a way to avoid it.",
      "revId": "c5254b52e57e7699b7b3f56127b4e420464e1d7b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1ab14d0d_7d792a2f",
        "filename": "ansible.cfg",
        "patchSetId": 9
      },
      "lineNbr": 12,
      "author": {
        "id": 1007069
      },
      "writtenOn": "2016-12-21T11:34:34Z",
      "side": 1,
      "message": "Sorin,\n\n100% agree on that, however octario was never tested in python3 and that should be separate review when we make appropriate changes when we move to python3.",
      "parentUuid": "1ab14d0d_3a73a84f",
      "revId": "c5254b52e57e7699b7b3f56127b4e420464e1d7b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1ab14d0d_b38923cd",
        "filename": "octario/lib/cli.py",
        "patchSetId": 9
      },
      "lineNbr": 111,
      "author": {
        "id": 1005170
      },
      "writtenOn": "2016-12-21T18:42:43Z",
      "side": 1,
      "message": "maybe grab exception here and either trace or re-raise the original exception, otherwise it just eats the exception, and you only get backtrace to here with no leads for what failed.",
      "revId": "c5254b52e57e7699b7b3f56127b4e420464e1d7b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1ab14d0d_4e8d967a",
        "filename": "octario/lib/cli.py",
        "patchSetId": 9
      },
      "lineNbr": 111,
      "author": {
        "id": 1007069
      },
      "writtenOn": "2016-12-21T20:08:07Z",
      "side": 1,
      "message": "Jon,\n\nI think the current behavior is correct, when I inject exception in the run() function then I get the full stack as the raise within Exception that has no arguments re-raises the last exception.\n\nHere is little test\n[1]\nCurrent way:\n$ octario -t pep8 /home/migi/Development/python-novaclient/\nINFO    Component: python-novaclient\nINFO    RHOS release: 5\nWARNING Inventory file does not exists: /home/migi/Development/OCTARIO_CLI/hosts\nWARNING Falling back to inventory: /home/migi/Development/OCTARIO_CLI/test/lib/python2.7/site-packages/octario/lib/../ansible/local_hosts\nINFO    Using ansible config from current dir: /home/migi/Development/OCTARIO_CLI/ansible.cfg\nTraceback (most recent call last):\n  File \"/home/migi/Development/OCTARIO_CLI/test/bin/octario\", line 11, in \u003cmodule\u003e\n    sys.exit(main())\n  File \"/home/migi/Development/OCTARIO_CLI/test/lib/python2.7/site-packages/octario/lib/cli.py\", line 106, in main\n    OctarioShell().main(args)\n  File \"/home/migi/Development/OCTARIO_CLI/test/lib/python2.7/site-packages/octario/lib/cli.py\", line 95, in main\n    ansible_playbook.run()\n  File \"/home/migi/Development/OCTARIO_CLI/test/lib/python2.7/site-packages/octario/lib/execute.py\", line 64, in run\n    raise ValueError(\u0027Test\u0027)\nValueError: Test\n\n\n\n\n[2] Modified to \"Exception, ex; raise ex\":\n$ octario -t pep8 /home/migi/Development/python-novaclient/\nINFO    Component: python-novaclient\nINFO    RHOS release: 5\nWARNING Inventory file does not exists: /home/migi/Development/OCTARIO_CLI/hosts\nWARNING Falling back to inventory: /home/migi/Development/OCTARIO_CLI/test/lib/python2.7/site-packages/octario/lib/../ansible/local_hosts\nINFO    Using ansible config from current dir: /home/migi/Development/OCTARIO_CLI/ansible.cfg\nTraceback (most recent call last):\n  File \"/home/migi/Development/OCTARIO_CLI/test/bin/octario\", line 11, in \u003cmodule\u003e\n    sys.exit(main())\n  File \"/home/migi/Development/OCTARIO_CLI/test/lib/python2.7/site-packages/octario/lib/cli.py\", line 112, in main\n    raise ex\nValueError: Test\n\n\n\nYou can see that what you are describing is second scenario, but currently implemented is first.",
      "parentUuid": "1ab14d0d_b38923cd",
      "revId": "c5254b52e57e7699b7b3f56127b4e420464e1d7b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1ab14d0d_8e65dee2",
        "filename": "setup.py",
        "patchSetId": 9
      },
      "lineNbr": 42,
      "author": {
        "id": 1004788
      },
      "writtenOn": "2016-12-21T19:54:40Z",
      "side": 1,
      "message": "hmm why?",
      "range": {
        "startLine": 42,
        "startChar": 18,
        "endLine": 42,
        "endChar": 30
      },
      "revId": "c5254b52e57e7699b7b3f56127b4e420464e1d7b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1ab14d0d_ce808649",
        "filename": "setup.py",
        "patchSetId": 9
      },
      "lineNbr": 42,
      "author": {
        "id": 1007069
      },
      "writtenOn": "2016-12-21T19:57:49Z",
      "side": 1,
      "message": "Didn\u0027t have other e-mail and took one from InfraRed. \nAlso thought we should add something else here.\nAnything better?",
      "parentUuid": "1ab14d0d_8e65dee2",
      "range": {
        "startLine": 42,
        "startChar": 18,
        "endLine": 42,
        "endChar": 30
      },
      "revId": "c5254b52e57e7699b7b3f56127b4e420464e1d7b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1ab14d0d_8e939ea3",
        "filename": "setup.py",
        "patchSetId": 9
      },
      "lineNbr": 42,
      "author": {
        "id": 1004788
      },
      "writtenOn": "2016-12-21T19:59:03Z",
      "side": 1,
      "message": "rhos-ci@redhat.com",
      "parentUuid": "1ab14d0d_ce808649",
      "range": {
        "startLine": 42,
        "startChar": 18,
        "endLine": 42,
        "endChar": 30
      },
      "revId": "c5254b52e57e7699b7b3f56127b4e420464e1d7b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}